CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    Tag NVARCHAR(50) NOT NULL,
    DisplayName NVARCHAR(100) NOT NULL,
    AvatarUrl NVARCHAR(500) NULL,
    CreatedAt DATETIME2 DEFAULT GETDATE()
);