CREATE TABLE Boards (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NULL,
    CreatedById INT NOT NULL,
    UpdatedById INT NOT NULL,

    CONSTRAINT FK_Boards_CreatedBy FOREIGN KEY (CreatedById) REFERENCES Users(Id),
    CONSTRAINT FK_Boards_UpdatedBy FOREIGN KEY (UpdatedById) REFERENCES Users(Id)
);