CREATE TABLE BoardMembers (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL,
    BoardId INT NOT NULL,
    Role NVARCHAR(50) NULL,
    JoinedAt DATETIME2 DEFAULT GETUTCDATE(),

    CONSTRAINT FK_BoardMembers_User FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT FK_BoardMembers_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);