CREATE TABLE Columns (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    BoardId INT NOT NULL,

    CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2 NULL,
    CreatedBy INT NOT NULL,
    UpdatedBy INT NULL,

    CONSTRAINT FK_Columns_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Columns_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id), 
    CONSTRAINT FK_Columns_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id)
);