CREATE TABLE Columns (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    BoardId INT NOT NULL,

    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 NULL,

    CONSTRAINT FK_Columns_Board FOREIGN KEY (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);