ALTER TABLE Boards 
ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Boards 
ADD Position INT NOT NULL DEFAULT 0;

ALTER TABLE Boards
ADD LastTimeOpenned DATETIME2 NOT NULL DEFAULT GETUTCDATE();
GO

ALTER TABLE [Columns] 
ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE [Columns] 
ADD Position INT NOT NULL DEFAULT 0;
GO

ALTER TABLE Cards 
ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Cards 
ADD IsCompleted BIT NOT NULL DEFAULT 0;

ALTER TABLE Cards 
ADD Position INT NOT NULL DEFAULT 0;
GO